<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Exceptions\StatusException.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PMatches.Common\PMatches.Common.csproj" />
    <ProjectReference Include="..\PMatches.Domain\PMatches.Domain.csproj" />
    <ProjectReference Include="..\PMatches.Persistence\PMatches.Persistence.csproj" />
  </ItemGroup>

</Project>
